package ru.bocharova.tm.api.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-07-23T22:22:32.111+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.api.tm.bocharova.ru/", name = "IUserEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface IUserEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/changeUserPasswordRequest", output = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/changeUserPasswordResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/changeUserPassword/Fault/AuthenticationSecurityException"), @FaultAction(className = DataValidateException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/changeUserPassword/Fault/DataValidateException")})
    @RequestWrapper(localName = "changeUserPassword", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.ChangeUserPassword")
    @ResponseWrapper(localName = "changeUserPasswordResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.ChangeUserPasswordResponse")
    public void changeUserPassword(
        @WebParam(name = "session", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.SessionDTO session,
        @WebParam(name = "user", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.UserDTO user
    ) throws AuthenticationSecurityException_Exception, DataValidateException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/getUserBySessionRequest", output = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/getUserBySessionResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/getUserBySession/Fault/AuthenticationSecurityException"), @FaultAction(className = DataValidateException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/getUserBySession/Fault/DataValidateException")})
    @RequestWrapper(localName = "getUserBySession", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.GetUserBySession")
    @ResponseWrapper(localName = "getUserBySessionResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.GetUserBySessionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.bocharova.tm.api.endpoint.UserDTO getUserBySession(
        @WebParam(name = "session", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.SessionDTO session
    ) throws AuthenticationSecurityException_Exception, DataValidateException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/findAllUserRequest", output = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/findAllUserResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/findAllUser/Fault/AuthenticationSecurityException"), @FaultAction(className = DataValidateException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/findAllUser/Fault/DataValidateException")})
    @RequestWrapper(localName = "findAllUser", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.FindAllUser")
    @ResponseWrapper(localName = "findAllUserResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.FindAllUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.bocharova.tm.api.endpoint.UserDTO> findAllUser(
        @WebParam(name = "session", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.SessionDTO session
    ) throws AuthenticationSecurityException_Exception, DataValidateException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/createUserRequest", output = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/createUserResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/createUser/Fault/AuthenticationSecurityException"), @FaultAction(className = DataValidateException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/createUser/Fault/DataValidateException")})
    @RequestWrapper(localName = "createUser", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.CreateUserResponse")
    public void createUser(
        @WebParam(name = "session", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.SessionDTO session,
        @WebParam(name = "user", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.UserDTO user
    ) throws AuthenticationSecurityException_Exception, DataValidateException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/editUserProfileRequest", output = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/editUserProfileResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/editUserProfile/Fault/AuthenticationSecurityException"), @FaultAction(className = DataValidateException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/editUserProfile/Fault/DataValidateException")})
    @RequestWrapper(localName = "editUserProfile", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.EditUserProfile")
    @ResponseWrapper(localName = "editUserProfileResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.EditUserProfileResponse")
    public void editUserProfile(
        @WebParam(name = "session", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.SessionDTO session,
        @WebParam(name = "user", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.UserDTO user
    ) throws AuthenticationSecurityException_Exception, DataValidateException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/findUserByLoginRequest", output = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/findUserByLoginResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/findUserByLogin/Fault/AuthenticationSecurityException"), @FaultAction(className = DataValidateException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/IUserEndpoint/findUserByLogin/Fault/DataValidateException")})
    @RequestWrapper(localName = "findUserByLogin", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.FindUserByLogin")
    @ResponseWrapper(localName = "findUserByLoginResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.FindUserByLoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.bocharova.tm.api.endpoint.UserDTO findUserByLogin(
        @WebParam(name = "session", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.SessionDTO session,
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login
    ) throws AuthenticationSecurityException_Exception, DataValidateException_Exception;
}
